# Generated by Django 5.0.7 on 2024-09-06 08:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_id', models.TextField(null=True)),
                ('pub_date', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('title', models.TextField(max_length=300, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published status')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('pub_date', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300, verbose_name='Title')),
                ('pub_date', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published')),
                ('content', models.JSONField(verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1100, verbose_name='Text')),
                ('spotify_url', models.URLField(null=True, verbose_name='Spotify URL')),
                ('url', models.URLField(verbose_name='Album URL')),
                ('band_name', models.CharField(max_length=50, verbose_name='Band name')),
                ('album_name', models.CharField(max_length=100, verbose_name='Album name')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('links', models.JSONField(verbose_name='Links to streamings')),
                ('is_published', models.BooleanField(default=False)),
                ('pub_date', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='api.post')),
            ],
        ),
    ]
