# Generated by Django 5.0.7 on 2024-09-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_album_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='substack_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='telegram_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
