# Generated by Django 5.0.7 on 2024-10-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_substack_content_post_telegram_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
    ]
