version: '3'

volumes:
  static:
  media:
  sqlite_data:
  pg_data:

services:
  db:
    image: postgres:13
    env_file: 
      - .env.prod
    volumes: 
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env.prod
    command: poetry run gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - static:/app/static
      - media:/app/media
      - sqlite_data:/app/db
    depends_on:
      - db
  frontend:
    build: ./frontend/
    image: albums_weekly_frontend:latest
    env_file: .env.prod
  
  gateway:
    build: ./nginx/
    env_file: .env.prod
    ports:
      - 8000:80
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - backend
      - frontend

